// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Configuration for loading a GGUF model.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ModelConfig {
  /// Absolute path to the `.gguf` model file on device storage.
  var modelPath: String
  /// Number of CPU threads to use for inference.
  var nThreads: Int64
  /// KV-cache context size in tokens. Larger values use more RAM.
  var contextSize: Int64
  /// Number of model layers to offload to GPU via Vulkan.
  /// Use [LlamaController.detectGpu] to get a device-appropriate value.
  /// Null or 0 = CPU only. 99 = full offload (clamped to model's layer count).
  var nGpuLayers: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ModelConfig? {
    let modelPath = pigeonVar_list[0] as! String
    let nThreads = pigeonVar_list[1] as! Int64
    let contextSize = pigeonVar_list[2] as! Int64
    let nGpuLayers: Int64? = nilOrValue(pigeonVar_list[3])

    return ModelConfig(
      modelPath: modelPath,
      nThreads: nThreads,
      contextSize: contextSize,
      nGpuLayers: nGpuLayers
    )
  }
  func toList() -> [Any?] {
    return [
      modelPath,
      nThreads,
      contextSize,
      nGpuLayers,
    ]
  }
}

/// A single message in a chat conversation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ChatMessage {
  /// Role of the message sender: `'system'`, `'user'`, or `'assistant'`.
  var role: String
  /// Text content of the message.
  var content: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChatMessage? {
    let role = pigeonVar_list[0] as! String
    let content = pigeonVar_list[1] as! String

    return ChatMessage(
      role: role,
      content: content
    )
  }
  func toList() -> [Any?] {
    return [
      role,
      content,
    ]
  }
}

/// Request for text generation
///
/// Generated class from Pigeon that represents data sent in messages.
struct GenerateRequest {
  var prompt: String
  var maxTokens: Int64
  var temperature: Double
  var topP: Double
  var topK: Int64
  var minP: Double
  var typicalP: Double
  var repeatPenalty: Double
  var frequencyPenalty: Double
  var presencePenalty: Double
  var repeatLastN: Int64
  var mirostat: Int64
  var mirostatTau: Double
  var mirostatEta: Double
  var seed: Int64? = nil
  var penalizeNewline: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GenerateRequest? {
    let prompt = pigeonVar_list[0] as! String
    let maxTokens = pigeonVar_list[1] as! Int64
    let temperature = pigeonVar_list[2] as! Double
    let topP = pigeonVar_list[3] as! Double
    let topK = pigeonVar_list[4] as! Int64
    let minP = pigeonVar_list[5] as! Double
    let typicalP = pigeonVar_list[6] as! Double
    let repeatPenalty = pigeonVar_list[7] as! Double
    let frequencyPenalty = pigeonVar_list[8] as! Double
    let presencePenalty = pigeonVar_list[9] as! Double
    let repeatLastN = pigeonVar_list[10] as! Int64
    let mirostat = pigeonVar_list[11] as! Int64
    let mirostatTau = pigeonVar_list[12] as! Double
    let mirostatEta = pigeonVar_list[13] as! Double
    let seed: Int64? = nilOrValue(pigeonVar_list[14])
    let penalizeNewline = pigeonVar_list[15] as! Bool

    return GenerateRequest(
      prompt: prompt,
      maxTokens: maxTokens,
      temperature: temperature,
      topP: topP,
      topK: topK,
      minP: minP,
      typicalP: typicalP,
      repeatPenalty: repeatPenalty,
      frequencyPenalty: frequencyPenalty,
      presencePenalty: presencePenalty,
      repeatLastN: repeatLastN,
      mirostat: mirostat,
      mirostatTau: mirostatTau,
      mirostatEta: mirostatEta,
      seed: seed,
      penalizeNewline: penalizeNewline
    )
  }
  func toList() -> [Any?] {
    return [
      prompt,
      maxTokens,
      temperature,
      topP,
      topK,
      minP,
      typicalP,
      repeatPenalty,
      frequencyPenalty,
      presencePenalty,
      repeatLastN,
      mirostat,
      mirostatTau,
      mirostatEta,
      seed,
      penalizeNewline,
    ]
  }
}

/// Request for chat generation with automatic template formatting.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ChatRequest {
  /// Conversation history including system, user, and assistant messages.
  var messages: [ChatMessage]
  /// Chat template name (e.g. `'chatml'`, `'llama3'`). Null = auto-detect from model filename.
  var template: String? = nil
  /// Maximum number of tokens to generate.
  var maxTokens: Int64
  var temperature: Double
  var topP: Double
  var topK: Int64
  var minP: Double
  var typicalP: Double
  var repeatPenalty: Double
  var frequencyPenalty: Double
  var presencePenalty: Double
  var repeatLastN: Int64
  var mirostat: Int64
  var mirostatTau: Double
  var mirostatEta: Double
  var seed: Int64? = nil
  var penalizeNewline: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ChatRequest? {
    let messages = pigeonVar_list[0] as! [ChatMessage]
    let template: String? = nilOrValue(pigeonVar_list[1])
    let maxTokens = pigeonVar_list[2] as! Int64
    let temperature = pigeonVar_list[3] as! Double
    let topP = pigeonVar_list[4] as! Double
    let topK = pigeonVar_list[5] as! Int64
    let minP = pigeonVar_list[6] as! Double
    let typicalP = pigeonVar_list[7] as! Double
    let repeatPenalty = pigeonVar_list[8] as! Double
    let frequencyPenalty = pigeonVar_list[9] as! Double
    let presencePenalty = pigeonVar_list[10] as! Double
    let repeatLastN = pigeonVar_list[11] as! Int64
    let mirostat = pigeonVar_list[12] as! Int64
    let mirostatTau = pigeonVar_list[13] as! Double
    let mirostatEta = pigeonVar_list[14] as! Double
    let seed: Int64? = nilOrValue(pigeonVar_list[15])
    let penalizeNewline = pigeonVar_list[16] as! Bool

    return ChatRequest(
      messages: messages,
      template: template,
      maxTokens: maxTokens,
      temperature: temperature,
      topP: topP,
      topK: topK,
      minP: minP,
      typicalP: typicalP,
      repeatPenalty: repeatPenalty,
      frequencyPenalty: frequencyPenalty,
      presencePenalty: presencePenalty,
      repeatLastN: repeatLastN,
      mirostat: mirostat,
      mirostatTau: mirostatTau,
      mirostatEta: mirostatEta,
      seed: seed,
      penalizeNewline: penalizeNewline
    )
  }
  func toList() -> [Any?] {
    return [
      messages,
      template,
      maxTokens,
      temperature,
      topP,
      topK,
      minP,
      typicalP,
      repeatPenalty,
      frequencyPenalty,
      presencePenalty,
      repeatLastN,
      mirostat,
      mirostatTau,
      mirostatEta,
      seed,
      penalizeNewline,
    ]
  }
}

/// Current KV-cache context usage for a loaded model.
///
/// Generated class from Pigeon that represents data sent in messages.
struct ContextInfo {
  /// Number of tokens currently occupying the KV cache.
  var tokensUsed: Int64
  /// Total KV-cache capacity in tokens (set at model load time).
  var contextSize: Int64
  /// Percentage of context used (0.0–100.0).
  var usagePercentage: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ContextInfo? {
    let tokensUsed = pigeonVar_list[0] as! Int64
    let contextSize = pigeonVar_list[1] as! Int64
    let usagePercentage = pigeonVar_list[2] as! Double

    return ContextInfo(
      tokensUsed: tokensUsed,
      contextSize: contextSize,
      usagePercentage: usagePercentage
    )
  }
  func toList() -> [Any?] {
    return [
      tokensUsed,
      contextSize,
      usagePercentage,
    ]
  }
}

/// GPU detection result
///
/// Generated class from Pigeon that represents data sent in messages.
struct GpuInfo {
  /// True only if Vulkan instance created AND compute queue confirmed
  var vulkanSupported: Bool
  /// e.g. "Adreno (TM) 740" or "Mali-G715". "None" if unsupported.
  var gpuName: String
  /// Vulkan API version integer (e.g. 4206592 = 1.3.0). -1 if unsupported.
  var vulkanApiVersion: Int64
  /// Largest VK_MEMORY_HEAP_DEVICE_LOCAL_BIT heap in bytes.
  /// On Android UMA this equals total system RAM — NOT dedicated VRAM.
  /// -1 if unknown.
  var deviceLocalMemoryBytes: Int64
  /// System free RAM from ActivityManager in bytes (before safety factor). -1 if unknown.
  var freeRamBytes: Int64
  /// Non-binding suggestion: 0, 16, or 99.
  /// llama.cpp clamps 99 to the model's actual layer count.
  /// Caller always makes the final decision.
  var recommendedGpuLayers: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GpuInfo? {
    let vulkanSupported = pigeonVar_list[0] as! Bool
    let gpuName = pigeonVar_list[1] as! String
    let vulkanApiVersion = pigeonVar_list[2] as! Int64
    let deviceLocalMemoryBytes = pigeonVar_list[3] as! Int64
    let freeRamBytes = pigeonVar_list[4] as! Int64
    let recommendedGpuLayers = pigeonVar_list[5] as! Int64

    return GpuInfo(
      vulkanSupported: vulkanSupported,
      gpuName: gpuName,
      vulkanApiVersion: vulkanApiVersion,
      deviceLocalMemoryBytes: deviceLocalMemoryBytes,
      freeRamBytes: freeRamBytes,
      recommendedGpuLayers: recommendedGpuLayers
    )
  }
  func toList() -> [Any?] {
    return [
      vulkanSupported,
      gpuName,
      vulkanApiVersion,
      deviceLocalMemoryBytes,
      freeRamBytes,
      recommendedGpuLayers,
    ]
  }
}

private class GeneratedMessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return ModelConfig.fromList(self.readValue() as! [Any?])
    case 130:
      return ChatMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return GenerateRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return ChatRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return ContextInfo.fromList(self.readValue() as! [Any?])
    case 134:
      return GpuInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class GeneratedMessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ModelConfig {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ChatMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? GenerateRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? ChatRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? ContextInfo {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? GpuInfo {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class GeneratedMessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GeneratedMessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GeneratedMessagesPigeonCodecWriter(data: data)
  }
}

class GeneratedMessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = GeneratedMessagesPigeonCodec(readerWriter: GeneratedMessagesPigeonCodecReaderWriter())
}


/// Host API (Dart calls Kotlin)
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol LlamaHostApi {
  /// Load a GGUF model
  func loadModel(config: ModelConfig, completion: @escaping (Result<Void, Error>) -> Void)
  /// Start text generation (tokens streamed via FlutterApi)
  func generate(request: GenerateRequest, completion: @escaping (Result<Void, Error>) -> Void)
  /// Start chat generation with automatic template formatting
  func generateChat(request: ChatRequest, completion: @escaping (Result<Void, Error>) -> Void)
  /// Get list of supported chat templates
  func getSupportedTemplates() throws -> [String]
  /// Stop current generation
  func stop(completion: @escaping (Result<Void, Error>) -> Void)
  /// Unload model and free resources
  func dispose(completion: @escaping (Result<Void, Error>) -> Void)
  /// Check if model is loaded
  func isModelLoaded() throws -> Bool
  /// Get current context usage information
  func getContextInfo() throws -> ContextInfo
  /// Clear conversation context (keeps model loaded)
  func clearContext(completion: @escaping (Result<Void, Error>) -> Void)
  /// Set the system prompt token length for smart context management
  func setSystemPromptLength(length: Int64) throws
  /// Register a custom template
  func registerCustomTemplate(name: String, content: String) throws
  /// Unregister a custom template
  func unregisterCustomTemplate(name: String) throws
  /// Detect GPU capabilities. Returns Vulkan device info and a non-binding
  /// recommendedGpuLayers value. Caller decides actual gpuLayers to use.
  func detectGpu(completion: @escaping (Result<GpuInfo, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class LlamaHostApiSetup {
  static var codec: FlutterStandardMessageCodec { GeneratedMessagesPigeonCodec.shared }
  /// Sets up an instance of `LlamaHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: LlamaHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Load a GGUF model
    let loadModelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.loadModel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadModelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! ModelConfig
        api.loadModel(config: configArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      loadModelChannel.setMessageHandler(nil)
    }
    /// Start text generation (tokens streamed via FlutterApi)
    let generateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.generate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GenerateRequest
        api.generate(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateChannel.setMessageHandler(nil)
    }
    /// Start chat generation with automatic template formatting
    let generateChatChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.generateChat\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateChatChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ChatRequest
        api.generateChat(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateChatChannel.setMessageHandler(nil)
    }
    /// Get list of supported chat templates
    let getSupportedTemplatesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.getSupportedTemplates\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getSupportedTemplatesChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getSupportedTemplates()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getSupportedTemplatesChannel.setMessageHandler(nil)
    }
    /// Stop current generation
    let stopChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.stop\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopChannel.setMessageHandler { _, reply in
        api.stop { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopChannel.setMessageHandler(nil)
    }
    /// Unload model and free resources
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.dispose\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        api.dispose { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
    /// Check if model is loaded
    let isModelLoadedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.isModelLoaded\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isModelLoadedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isModelLoaded()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isModelLoadedChannel.setMessageHandler(nil)
    }
    /// Get current context usage information
    let getContextInfoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.getContextInfo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getContextInfoChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getContextInfo()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getContextInfoChannel.setMessageHandler(nil)
    }
    /// Clear conversation context (keeps model loaded)
    let clearContextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.clearContext\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearContextChannel.setMessageHandler { _, reply in
        api.clearContext { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      clearContextChannel.setMessageHandler(nil)
    }
    /// Set the system prompt token length for smart context management
    let setSystemPromptLengthChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.setSystemPromptLength\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setSystemPromptLengthChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let lengthArg = args[0] as! Int64
        do {
          try api.setSystemPromptLength(length: lengthArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setSystemPromptLengthChannel.setMessageHandler(nil)
    }
    /// Register a custom template
    let registerCustomTemplateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.registerCustomTemplate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerCustomTemplateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        let contentArg = args[1] as! String
        do {
          try api.registerCustomTemplate(name: nameArg, content: contentArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      registerCustomTemplateChannel.setMessageHandler(nil)
    }
    /// Unregister a custom template
    let unregisterCustomTemplateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.unregisterCustomTemplate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      unregisterCustomTemplateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nameArg = args[0] as! String
        do {
          try api.unregisterCustomTemplate(name: nameArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      unregisterCustomTemplateChannel.setMessageHandler(nil)
    }
    /// Detect GPU capabilities. Returns Vulkan device info and a non-binding
    /// recommendedGpuLayers value. Caller decides actual gpuLayers to use.
    let detectGpuChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.detectGpu\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      detectGpuChannel.setMessageHandler { _, reply in
        api.detectGpu { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      detectGpuChannel.setMessageHandler(nil)
    }
  }
}
/// Flutter API (Kotlin calls Dart)
///
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol LlamaFlutterApiProtocol {
  /// Stream token to Dart
  func onToken(token tokenArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Generation completed
  func onDone(completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Error occurred
  func onError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  /// Loading progress (0.0 to 1.0)
  func onLoadProgress(progress progressArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class LlamaFlutterApi: LlamaFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: GeneratedMessagesPigeonCodec {
    return GeneratedMessagesPigeonCodec.shared
  }
  /// Stream token to Dart
  func onToken(token tokenArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onToken\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([tokenArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Generation completed
  func onDone(completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onDone\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage(nil) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Error occurred
  func onError(error errorArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  /// Loading progress (0.0 to 1.0)
  func onLoadProgress(progress progressArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onLoadProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
