// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// Configuration for loading a GGUF model.
class ModelConfig {
  ModelConfig({
    required this.modelPath,
    required this.nThreads,
    required this.contextSize,
    this.nGpuLayers,
    this.mmprojPath,
  });

  /// Absolute path to the `.gguf` model file on device storage.
  String modelPath;

  /// Absolute path to the vision projector file (`mmproj`) for VL models.
  String? mmprojPath;

  /// Number of CPU threads to use for inference.
  int nThreads;

  /// KV-cache context size in tokens. Larger values use more RAM.
  int contextSize;

  /// Number of model layers to offload to GPU via Vulkan.
  /// Use [LlamaController.detectGpu] to get a device-appropriate value.
  /// Null or 0 = CPU only. 99 = full offload (clamped to model's layer count).
  int? nGpuLayers;

  Object encode() {
    return <Object?>[
      modelPath,
      nThreads,
      contextSize,
      nGpuLayers,
      mmprojPath,
    ];
  }

  static ModelConfig decode(Object result) {
    result as List<Object?>;
    return ModelConfig(
      modelPath: result[0]! as String,
      nThreads: result[1]! as int,
      contextSize: result[2]! as int,
      nGpuLayers: result[3] as int?,
      mmprojPath: result[4] as String?,
    );
  }
}

/// A single message in a chat conversation.
class ChatMessage {
  ChatMessage({
    required this.role,
    required this.content,
    this.imagePath,
  });

  /// Role of the message sender: `'system'`, `'user'`, or `'assistant'`.
  String role;

  /// Text content of the message.
  String content;

  /// Absolute path to an image file for vision-language models.
  String? imagePath;

  Object encode() {
    return <Object?>[
      role,
      content,
      imagePath,
    ];
  }

  static ChatMessage decode(Object result) {
    result as List<Object?>;
    return ChatMessage(
      role: result[0]! as String,
      content: result[1]! as String,
      imagePath: result[2] as String?,
    );
  }
}

/// Request for text generation
class GenerateRequest {
  GenerateRequest({
    required this.prompt,
    required this.maxTokens,
    required this.temperature,
    required this.topP,
    required this.topK,
    required this.minP,
    required this.typicalP,
    required this.repeatPenalty,
    required this.frequencyPenalty,
    required this.presencePenalty,
    required this.repeatLastN,
    required this.mirostat,
    required this.mirostatTau,
    required this.mirostatEta,
    this.seed,
    required this.penalizeNewline,
  });

  String prompt;

  int maxTokens;

  double temperature;

  double topP;

  int topK;

  double minP;

  double typicalP;

  double repeatPenalty;

  double frequencyPenalty;

  double presencePenalty;

  int repeatLastN;

  int mirostat;

  double mirostatTau;

  double mirostatEta;

  int? seed;

  bool penalizeNewline;

  Object encode() {
    return <Object?>[
      prompt,
      maxTokens,
      temperature,
      topP,
      topK,
      minP,
      typicalP,
      repeatPenalty,
      frequencyPenalty,
      presencePenalty,
      repeatLastN,
      mirostat,
      mirostatTau,
      mirostatEta,
      seed,
      penalizeNewline,
    ];
  }

  static GenerateRequest decode(Object result) {
    result as List<Object?>;
    return GenerateRequest(
      prompt: result[0]! as String,
      maxTokens: result[1]! as int,
      temperature: result[2]! as double,
      topP: result[3]! as double,
      topK: result[4]! as int,
      minP: result[5]! as double,
      typicalP: result[6]! as double,
      repeatPenalty: result[7]! as double,
      frequencyPenalty: result[8]! as double,
      presencePenalty: result[9]! as double,
      repeatLastN: result[10]! as int,
      mirostat: result[11]! as int,
      mirostatTau: result[12]! as double,
      mirostatEta: result[13]! as double,
      seed: result[14] as int?,
      penalizeNewline: result[15]! as bool,
    );
  }
}

/// Request for chat generation with automatic template formatting.
class ChatRequest {
  ChatRequest({
    required this.messages,
    this.template,
    required this.maxTokens,
    required this.temperature,
    required this.topP,
    required this.topK,
    required this.minP,
    required this.typicalP,
    required this.repeatPenalty,
    required this.frequencyPenalty,
    required this.presencePenalty,
    required this.repeatLastN,
    required this.mirostat,
    required this.mirostatTau,
    required this.mirostatEta,
    this.seed,
    required this.penalizeNewline,
  });

  /// Conversation history including system, user, and assistant messages.
  List<ChatMessage> messages;

  /// Chat template name (e.g. `'chatml'`, `'llama3'`). Null = auto-detect from model filename.
  String? template;

  /// Maximum number of tokens to generate.
  int maxTokens;

  double temperature;

  double topP;

  int topK;

  double minP;

  double typicalP;

  double repeatPenalty;

  double frequencyPenalty;

  double presencePenalty;

  int repeatLastN;

  int mirostat;

  double mirostatTau;

  double mirostatEta;

  int? seed;

  bool penalizeNewline;

  Object encode() {
    return <Object?>[
      messages,
      template,
      maxTokens,
      temperature,
      topP,
      topK,
      minP,
      typicalP,
      repeatPenalty,
      frequencyPenalty,
      presencePenalty,
      repeatLastN,
      mirostat,
      mirostatTau,
      mirostatEta,
      seed,
      penalizeNewline,
    ];
  }

  static ChatRequest decode(Object result) {
    result as List<Object?>;
    return ChatRequest(
      messages: (result[0] as List<Object?>?)!.cast<ChatMessage>(),
      template: result[1] as String?,
      maxTokens: result[2]! as int,
      temperature: result[3]! as double,
      topP: result[4]! as double,
      topK: result[5]! as int,
      minP: result[6]! as double,
      typicalP: result[7]! as double,
      repeatPenalty: result[8]! as double,
      frequencyPenalty: result[9]! as double,
      presencePenalty: result[10]! as double,
      repeatLastN: result[11]! as int,
      mirostat: result[12]! as int,
      mirostatTau: result[13]! as double,
      mirostatEta: result[14]! as double,
      seed: result[15] as int?,
      penalizeNewline: result[16]! as bool,
    );
  }
}

/// Current KV-cache context usage for a loaded model.
class ContextInfo {
  ContextInfo({
    required this.tokensUsed,
    required this.contextSize,
    required this.usagePercentage,
  });

  /// Number of tokens currently occupying the KV cache.
  int tokensUsed;

  /// Total KV-cache capacity in tokens (set at model load time).
  int contextSize;

  /// Percentage of context used (0.0–100.0).
  double usagePercentage;

  Object encode() {
    return <Object?>[
      tokensUsed,
      contextSize,
      usagePercentage,
    ];
  }

  static ContextInfo decode(Object result) {
    result as List<Object?>;
    return ContextInfo(
      tokensUsed: result[0]! as int,
      contextSize: result[1]! as int,
      usagePercentage: result[2]! as double,
    );
  }
}

/// GPU detection result
class GpuInfo {
  GpuInfo({
    required this.vulkanSupported,
    required this.gpuName,
    required this.vulkanApiVersion,
    required this.deviceLocalMemoryBytes,
    required this.freeRamBytes,
    required this.recommendedGpuLayers,
  });

  /// True only if Vulkan instance created AND compute queue confirmed
  bool vulkanSupported;

  /// e.g. "Adreno (TM) 740" or "Mali-G715". "None" if unsupported.
  String gpuName;

  /// Vulkan API version integer (e.g. 4206592 = 1.3.0). -1 if unsupported.
  int vulkanApiVersion;

  /// Largest VK_MEMORY_HEAP_DEVICE_LOCAL_BIT heap in bytes.
  /// On Android UMA this equals total system RAM — NOT dedicated VRAM.
  /// -1 if unknown.
  int deviceLocalMemoryBytes;

  /// System free RAM from ActivityManager in bytes (before safety factor). -1 if unknown.
  int freeRamBytes;

  /// Non-binding suggestion: 0, 16, or 99.
  /// llama.cpp clamps 99 to the model's actual layer count.
  /// Caller always makes the final decision.
  int recommendedGpuLayers;

  Object encode() {
    return <Object?>[
      vulkanSupported,
      gpuName,
      vulkanApiVersion,
      deviceLocalMemoryBytes,
      freeRamBytes,
      recommendedGpuLayers,
    ];
  }

  static GpuInfo decode(Object result) {
    result as List<Object?>;
    return GpuInfo(
      vulkanSupported: result[0]! as bool,
      gpuName: result[1]! as String,
      vulkanApiVersion: result[2]! as int,
      deviceLocalMemoryBytes: result[3]! as int,
      freeRamBytes: result[4]! as int,
      recommendedGpuLayers: result[5]! as int,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ModelConfig) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is ChatMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is GenerateRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is ChatRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ContextInfo) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GpuInfo) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return ModelConfig.decode(readValue(buffer)!);
      case 130: 
        return ChatMessage.decode(readValue(buffer)!);
      case 131: 
        return GenerateRequest.decode(readValue(buffer)!);
      case 132: 
        return ChatRequest.decode(readValue(buffer)!);
      case 133: 
        return ContextInfo.decode(readValue(buffer)!);
      case 134: 
        return GpuInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API (Dart calls Kotlin)
class LlamaHostApi {
  /// Constructor for [LlamaHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  LlamaHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Load a GGUF model
  Future<void> loadModel(ModelConfig config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.loadModel$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Start text generation (tokens streamed via FlutterApi)
  Future<void> generate(GenerateRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.generate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Start chat generation with automatic template formatting
  Future<void> generateChat(ChatRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.generateChat$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Get list of supported chat templates
  Future<List<String>> getSupportedTemplates() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.getSupportedTemplates$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<String>();
    }
  }

  /// Stop current generation
  Future<void> stop() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.stop$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Unload model and free resources
  Future<void> dispose() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.dispose$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Check if model is loaded
  Future<bool> isModelLoaded() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.isModelLoaded$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Get current context usage information
  Future<ContextInfo> getContextInfo() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.getContextInfo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ContextInfo?)!;
    }
  }

  /// Clear conversation context (keeps model loaded)
  Future<void> clearContext() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.clearContext$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Set the system prompt token length for smart context management
  Future<void> setSystemPromptLength(int length) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.setSystemPromptLength$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[length]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Register a custom template
  Future<void> registerCustomTemplate(String name, String content) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.registerCustomTemplate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name, content]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Unregister a custom template
  Future<void> unregisterCustomTemplate(String name) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.unregisterCustomTemplate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[name]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Detect GPU capabilities. Returns Vulkan device info and a non-binding
  /// recommendedGpuLayers value. Caller decides actual gpuLayers to use.
  Future<GpuInfo> detectGpu() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.llama_flutter_android.LlamaHostApi.detectGpu$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as GpuInfo?)!;
    }
  }
}

/// Flutter API (Kotlin calls Dart)
abstract class LlamaFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Stream token to Dart
  void onToken(String token);

  /// Generation completed
  void onDone();

  /// Error occurred
  void onError(String error);

  /// Loading progress (0.0 to 1.0)
  void onLoadProgress(double progress);

  static void setUp(LlamaFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onToken$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onToken was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_token = (args[0] as String?);
          assert(arg_token != null,
              'Argument for dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onToken was null, expected non-null String.');
          try {
            api.onToken(arg_token!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onDone$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          try {
            api.onDone();
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onError$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onError was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final String? arg_error = (args[0] as String?);
          assert(arg_error != null,
              'Argument for dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onError was null, expected non-null String.');
          try {
            api.onError(arg_error!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onLoadProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onLoadProgress was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final double? arg_progress = (args[0] as double?);
          assert(arg_progress != null,
              'Argument for dev.flutter.pigeon.llama_flutter_android.LlamaFlutterApi.onLoadProgress was null, expected non-null double.');
          try {
            api.onLoadProgress(arg_progress!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
